Repository irumi-dgu/irumi-client, pull requests merged in 2024-04, with the labels that each got.

#2 Feature/1
  package-lock.json
  package.json
  src/App.jsx
  src/assets/fonts/Dongguk.woff
  src/assets/fonts/Pretendard.woff
  src/components/atoms/button/Button.jsx
  src/components/molecules/buttonList/ButtonList.jsx
  src/components/organisms/buttonSetting/ButtonSetting.jsx
  src/components/organisms/header/Header.jsx
  src/components/templetes/fixView/FixView.jsx
  src/main.jsx
  src/recoil/theme.jsx
  src/style/fontStyle.css
  src/style/globalStyle.js
  src/style/theme.js
Labels: enhancement, SSH

#6 :sparkles: feat: 소원 작성 페이지-배경지 변경-#5
  src/assets/image/WishWrite/DayGradientBg.png
  src/assets/image/WishWrite/NightGradientBg.png
  src/assets/image/WishWrite/SunsetGradientBg.png
  src/components/organisms/Background/GradientBackground.jsx
  src/pages/wishWrite/wishWrite.jsx
  src/router.jsx
Labels: enhancement, OCJ

#8 Feature - main Page
  package-lock.json
  package.json
  public/img/fixBg/DAY.png
  public/img/fixBg/NIGHT.png
  public/img/fixBg/SUNSET.png
  public/img/wishCard/blue_default.png
  public/img/wishCard/blue_light.png
  public/img/wishCard/green_default.png
  public/img/wishCard/green_light.png
  public/img/wishCard/pink_default.png
  public/img/wishCard/pink_light.png
  public/img/wishCard/purple_default.png
  public/img/wishCard/purple_light.png
  public/img/wishCard/yellow_difault.png
  public/img/wishCard/yellow_light.png
  src/App.jsx
  src/components/atoms/button/Button.jsx
  src/components/common/atoms/button/Button.jsx
  src/components/common/atoms/emSizeChlid/EmSizeChlid.jsx
  src/components/common/atoms/emSizeChlid/style.jsx
  src/components/common/atoms/wishCard/WishCard.jsx
  src/components/common/molecules/buttonList/ButtonList.jsx
  src/components/common/molecules/emSizeParent/EmSizeParent.jsx
  src/components/common/organisms/Background/GradientBackground.jsx
  src/components/common/organisms/buttonSetting/ButtonSetting.jsx
  src/components/common/templetes/fixView/FixView.jsx
  src/components/main/atoms/lightBanner/LightBanner.jsx
  src/components/main/atoms/mainTextLabel/MainTextLabel.jsx
  src/components/main/molecules/wishCardSwiper/WishCardSwiper.jsx
  src/components/main/molecules/wishCardSwiper/swiper.css
  src/components/templetes/fixView/FixView.jsx
  src/pages/main/Main.jsx
  src/pages/wishWrite/wishWrite.jsx
  src/recoil/heightSize.jsx
  src/style/theme.js
Labels: enhancement, SSH

#14 💄 fix: BackBtn, header의 em -> px로 수정
  public/common/backBtnImg.png
  src/components/common/atoms/button/BackBtn.jsx
  src/components/common/molecules/header/header.jsx
  src/pages/wishWrite/lanternWrite.jsx
  src/router.jsx
Labels: OCJ

#17 :sparkles: #13 feat: 연꽃 색상, 소원지 컴포넌트 및 페이지
  public/img/Lantern/Big_blue.png
  public/img/Lantern/Big_green.png
  public/img/Lantern/Big_pink.png
  public/img/Lantern/Big_purple.png
  public/img/Lantern/Big_yellow.png
  public/img/Lantern/Small_off_blue.png
  public/img/Lantern/Small_off_green.png
  public/img/Lantern/Small_off_pink.png
  public/img/Lantern/Small_off_purple.png
  public/img/Lantern/Small_off_yellow.png
  public/img/Lantern/Small_on_blue.png
  public/img/Lantern/Small_on_green.png
  public/img/Lantern/Small_on_pink.png
  public/img/Lantern/Small_on_purple.png
  public/img/Lantern/Small_on_yellow.png
  public/img/Lantern/pw_off.png
  public/img/Lantern/pw_on.png
  src/components/lanternWrite/atom/DescriptionText.jsx
  src/components/lanternWrite/atom/button.jsx
  src/components/lanternWrite/atom/input.jsx
  src/components/lanternWrite/atom/lanternPw.jsx
  src/components/lanternWrite/molecules/LanternColorChoice.jsx
  src/components/lanternWrite/molecules/LanternColorConfirm.jsx
  src/components/lanternWrite/organisms/lanternWishPaper.jsx
  src/pages/Lantern/LanternColorPage.jsx
  src/pages/Lantern/LanternWrite.jsx
  src/pages/wishWrite/lanternWrite.jsx
  src/recoil/lanternColor.jsx
  src/recoil/lanternContent.jsx
  src/router.jsx
Labels: enhancement, OCJ

#21 :sparkles: feature: 연등 게시/디테일 api, 신고, 좋아요, 삭제
  public/img/Lantern/DAY.png
  public/img/Lantern/Dot.png
  public/img/Lantern/NIGHT.png
  public/img/Lantern/SUNSET.png
  public/img/Lantern/checked.png
  public/img/Lantern/like.png
  public/img/Lantern/like_fill.png
  public/img/lanternCard/blue_false.png
  public/img/lanternCard/blue_true.png
  public/img/lanternCard/green_false.png
  public/img/lanternCard/green_true.png
  public/img/lanternCard/pink_false.png
  public/img/lanternCard/pink_true.png
  public/img/lanternCard/purple_false.png
  public/img/lanternCard/purple_true.png
  public/img/lanternCard/yellow_false.png
  public/img/lanternCard/yellow_true.png
  src/apis/api/deleteLantern.js
  src/apis/api/lanternDetail.js
  src/apis/api/lanternPost.js
  src/apis/api/likeBtn.js
  src/apis/api/postReport.js
  src/components/common/atoms/lanternCard/LanternCard.jsx
  src/components/common/organisms/Background/LanternDetailBg.jsx
  src/components/lanternWrite/atom/ModalBackground.jsx
  src/components/lanternWrite/atom/likeBtn.jsx
  src/components/lanternWrite/organisms/CheckDeleteModal.jsx
  src/components/lanternWrite/organisms/DeleteModal.jsx
  src/components/lanternWrite/organisms/PwModal.jsx
  src/components/lanternWrite/organisms/ReportAlertModal.jsx
  src/components/lanternWrite/organisms/ReportModal.jsx
  src/components/lanternWrite/organisms/ReportedAlertModal.jsx
  src/components/lanternWrite/organisms/confirmModal.jsx
  src/components/lanternWrite/organisms/moreModal.jsx
  src/pages/Lantern/LanternColorPage.jsx
  src/pages/Lantern/LanternDetail.jsx
  src/pages/Lantern/LanternWrite.jsx
  src/router.jsx
Labels: enhancement

#26 등불 날리기
  public/icon/pen.svg
  public/img/Lamp/lamp_head.png
  public/img/Lamp/lamp_light.png
  public/img/Lamp/text.png
  src/components/common/atoms/button/RoundBtn.jsx
  src/components/common/atoms/lanternCard/LanternCard.jsx
  src/components/common/molecules/buttonList/ButtonList.jsx
  src/components/lampFly/atoms/LampDrag.jsx
  src/components/lampFly/atoms/LampImage.jsx
  src/components/lampFly/molecules/LampImageContainer.jsx
  src/pages/lamp/FlyLampPage.jsx
  src/pages/lamp/LampFlyPage.jsx
  src/pages/lanterns/LanternsPage.jsx
  src/router.jsx
Labels: enhancement, SSH

#32 ✏️ Fix - LanternsPage 인기순 정렬
  src/pages/lanterns/LanternsPage.jsx
Labels: enhancement, SSH

#34 Feat - lanternSearchPage
  public/img/scrollBg/DAY.png
  public/img/scrollBg/NIGHT.png
  public/img/scrollBg/SUNSET.png
  src/App.jsx
  src/apis/api/lantern.js
  src/components/common/molecules/buttonList/ButtonList.jsx
  src/components/dev/handleTheme/HandleTheme.jsx
  src/emun/sort.js
  src/pages/lanterns/LanternsPage.jsx
  src/pages/lanterns/LanternsSearchPage.jsx
  src/router.jsx
Labels: bug, SSH

#46 Feature/qa
  index.html
  package.json
  public/common/backBtnImg.png
  public/img/Fortune/Frame 6546.png
  public/img/Fortune/lightlotus.png
  public/img/Fortune/lotus.png
  src/components/common/atoms/button/BackBtn.jsx
  src/components/common/atoms/button/Button.jsx
  src/components/common/atoms/searchBar/SearchBar.jsx
  src/components/common/molecules/buttonList/ButtonList.jsx
  src/components/common/molecules/header/SearchHeader.jsx
  src/components/common/molecules/header/header.jsx
  src/components/fortune/atoms/MyBtn.jsx
  src/components/lamp/atoms/LampBanner.jsx
  src/components/lamp/atoms/LampTheme.jsx
  src/components/lanternWrite/atom/button.jsx
  src/pages/fotrune/FortuneIntroPage.jsx
  src/pages/fotrune/FortuneLeafPage.jsx
  src/pages/lamp/LampMainPage.jsx
  src/pages/lamp/LampWritePage.jsx
  src/pages/lantern/LanternColorPage.jsx
  src/pages/lantern/LanternWritePage.jsx
Labels: bug, SSH

#49 :bug: 좋아요 중복 해결
  src/apis/api/lanternDetail.js
  src/apis/api/likeBtn.js
  src/pages/lantern/LanternDetailPage.jsx
Labels: bug, OCJ

#50 backbtn 조정 (스타일, 경로) / wishPaper textarea 변경
  index.html
  public/img/favicon.png
  public/img/ogimg.png
  src/apis/api/likeBtn.js
  src/components/common/atoms/button/BackBtn.jsx
  src/components/common/molecules/header/header.jsx
  src/components/lanternWrite/atom/DescriptionText.jsx
  src/components/lanternWrite/atom/ModalBg.jsx
  src/components/lanternWrite/atom/WishPaperInput.jsx
  src/components/lanternWrite/atom/button.jsx
  src/components/lanternWrite/atom/input.jsx
  src/components/lanternWrite/atom/lanternPw.jsx
  src/components/lanternWrite/atom/likeBtn.jsx
  src/components/lanternWrite/molecules/LanternColorChoice.jsx
  src/components/lanternWrite/molecules/LanternColorConfirm.jsx
  src/components/lanternWrite/organisms/PwModal.jsx
  src/components/lanternWrite/organisms/ReportAlertModal.jsx
  src/components/lanternWrite/organisms/ReportModal.jsx
  src/components/lanternWrite/organisms/ReportedAlertModal.jsx
  src/components/lanternWrite/organisms/lanternWishPaper.jsx
  src/components/lanternWrite/organisms/moreModal.jsx
  src/pages/lantern/LanternColorPage.jsx
  src/pages/lantern/LanternDetailPage.jsx
  src/pages/lantern/LanternWritePage.jsx
  src/pages/lantern/style.jsx
Labels: OCJ

#66 QA 반영
  src/App.jsx
  src/components/common/atoms/searchBar/SearchBar.jsx
  src/components/lampFly/molecules/LampImageContainer.jsx
  src/components/main/atoms/lamplightBanner/LamplightBanner.jsx
  src/pages/fotrune/FortuneIntroPage.jsx
  src/pages/fotrune/FortuneLeafPage.jsx
  src/style/animation.css
  src/style/theme.js
Labels: enhancement, SSH
